In [2]:
import pandas as pd

In [4]:
balls = pd.read_csv("./train/train_ball_by_ball_data.csv")
balls['player_dismissed_id'] = balls['player_dismissed_id'].fillna(0)
balls['player_dismissed'] = balls['player_dismissed'].fillna("Not Out")
balls['dismissal_kind'] = balls['dismissal_kind'].fillna("Not Out")

#Adding Season# and Match Number to the above dataframe
balls['season'] = balls.match_id.str[:4]
balls['match_number'] = balls.match_id.str[5:]

In [5]:
#Total runs by all batsmen:
BatsmanTotalRuns = balls.groupby('batsman')["batsman_runs"].sum().sort_values(ascending=False)
BatsmanTotalRuns = BatsmanTotalRuns.reset_index(name='Runs')

#Total Matches by all batsmen:
BatsmanTotalMatches = balls.groupby('batsman')["match_id"].nunique().sort_values(ascending=False)
BatsmanTotalMatches = BatsmanTotalMatches.reset_index(name='Matches')

#Total Balls by all batsmen:
BatsmanTotalBalls = balls.groupby('batsman')["ball"].count().sort_values(ascending=False)
BatsmanTotalBalls = BatsmanTotalBalls.reset_index(name='BallsFaced')

#Joining the 3 dataframes together:
BatsmanTotalRuns = BatsmanTotalRuns.merge(BatsmanTotalMatches, how ='inner', on="batsman")
BatsmanTotalRuns = BatsmanTotalRuns.merge(BatsmanTotalBalls, how ='inner', on="batsman")

#Adding a column for strike rates of respective players
BatsmanTotalRuns["StrikeRate"] = ((BatsmanTotalRuns["Runs"]/BatsmanTotalRuns["BallsFaced"])*100).round(2)

In [6]:
#Highest runs scored by each batsmen:
Highest = balls.groupby(['batsman','match_id'])["batsman_runs"].sum()
Highest = Highest.reset_index(name='Highest')
Highest = Highest.groupby('batsman')['Highest'].max()
Highest = Highest.reset_index(name='HighestScore')

#Merging Highest runs to the existing dataframe, BatsmanTotalRuns:
BatsmanTotalRuns = BatsmanTotalRuns.merge(Highest, how ='inner', on="batsman")

In [7]:
#Number of Fours by Every Player
FoursDF = balls[balls.batsman_runs == 4] 
Fours = FoursDF.groupby('batsman')['batsman_runs'].count()
Fours = Fours.reset_index(name='Fours')
BatsmanTotalRuns = BatsmanTotalRuns.merge(Fours, how ='inner', on="batsman")


#Number of Sixes by Every Player
SixesDF = balls[balls.batsman_runs == 6] 
Sixes = SixesDF.groupby('batsman')['batsman_runs'].count()
Sixes = Sixes.reset_index(name='Sixes')
BatsmanTotalRuns = BatsmanTotalRuns.merge(Sixes, how ='inner', on="batsman")
BatsmanTotalRuns

,batsman,Runs,Matches,BallsFaced,StrikeRate,HighestScore,Fours,Sixes
0,Suresh Raina,4548,157,3369,135.00,100,402,174
1,Virat Kohli,4423,141,3494,126.59,113,384,160
2,Rohit Sharma,4207,153,3274,128.50,109,354,173
3,Gautam Gambhir,4132,146,3433,120.36,93,484,58
4,David Warner,4014,114,2902,138.32,126,401,160
5,Robin Uthappa,3778,143,2960,127.64,87,377,125
6,Chris Gayle,3651,100,2532,144.19,175,297,266
7,Shikhar Dhawan,3561,126,3005,118.50,95,401,71
8,Mahendra Singh Dhoni,3560,143,2680,132.84,70,251,156
9,AB De Villiers,3486,118,2402,145.13,133,287,158
10,Ajinkya Rahane,3057,105,2602,117.49,103,320,60
11,Yusuf Pathan,2922,133,2076,140.75,100,240,149
12,Dinesh Karthik,2903,134,2360,123.01,86,286,71
13,Brendon McCullum,2755,103,2181,126.32,158,277,124
14,Virender Sehwag,2728,104,1833,148.83,122,334,106
15,Shane Watson,2628,98,1949,134.84,104,258,122
16,Yuvraj Singh,2591,116,2050,126.39,83,205,141
17,Murali Vijay,2511,99,2092,120.03,127,237,89
18,Shaun Marsh,2489,69,1913,130.11,115,269,78
19,Jacques Kallis,2427,95,2291,105.94,89,255,44
20,Ambati Rayudu,2416,105,1964,123.01,81,205,79
21,Dwayne Smith,2385,88,1803,132.28,87,245,117
22,Kieron Pollard,2354,112,1674,140.62,78,158,148
23,Sachin Tendulkar,2334,78,2044,114.19,100,296,29
24,Parthiv Patel,2322,116,2060,112.72,81,297,35
25,Manish Pandey,2223,95,1901,116.94,114,197,65
26,Rahul Dravid,2174,82,1918,113.35,75,269,28
27,Adam Gilchrist,2069,80,1555,133.05,109,239,92
28,J P Duminy,1993,73,1634,121.97,78,123,78
29,Michael Hussey,1977,58,1648,119.96,116,198,52
...,...,...,...,...,...,...,...,...
259,Asad Pathan,39,7,26,150.00,14,5,2
260,Jason Holder,38,5,32,118.75,16,4,2
261,Lakshmipathy Balaji,36,13,50,72.00,15,2,1
262,Sohail Tanvir,36,5,31,116.13,13,3,1
263,Kane Richardson,36,4,39,92.31,26,2,1
264,Joginder Sharma,36,5,30,120.00,16,1,2
265,Abu Nechim,36,6,27,133.33,18,4,1
266,Rahul Tewatia,35,3,24,145.83,16,4,1
267,Abhimanyu Mithun,34,6,26,130.77,11,4,1
268,Aditya Dole,34,2,23,147.83,30,3,1
269,Luke Ronchi,34,5,37,91.89,13,6,1
270,Anureet Singh,33,7,43,76.74,15,2,1
271,Robin Peterson,32,5,32,100.00,16,3,1
272,Vijay Zol,29,2,26,111.54,16,3,1
273,Basil Thampi,28,5,30,93.33,13,1,1
274,Justin Kemp,26,2,25,104.00,22,1,1
275,Aniket Choudhary,25,3,20,125.00,15,1,1
276,Jasprit Bumrah,25,6,27,92.59,16,1,1
277,Eklavya Dwivedi,24,2,15,160.00,19,2,2
278,Musavir Khote,24,3,22,109.09,9,2,1
279,Shaun Tait,23,5,26,88.46,11,1,1
280,Doug Bollinger,21,4,23,91.30,16,1,1
281,Alfonso Thomas,20,4,19,105.26,12,1,1
282,Rohan Raje,20,5,18,111.11,11,1,1
283,Pradeep Sahu,19,2,13,146.15,18,1,1
284,Vishnu Vinod,19,3,26,73.08,9,1,1
285,Rajesh Bishnoi,19,3,17,111.76,18,1,2
286,Johan van der Wath,18,3,17,105.88,14,1,1
287,Brad Haddin,18,1,11,163.64,18,2,1
288,Sean Abbott,15,2,13,115.38,14,1,1